language: php
sudo: required
dist: trusty
group: edge
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "hhvm-3.9"
  - "hhvm-3.12"

before_script:
  - composer self-update
  - composer install

after_success:
  - bash .ci/generate-api.sh

script:
  - composer run test

cache:
  directories:
    - vendor

notifications:
  on_success: never
  on_failure: never

env :
  global :
    secure : "R3XytmglnVJKevh9T7zpE0S2XhdYUr/DXYWfxNgnSbQo+SFBxiee1MqhCbmFAYPAwDexIkEeQUshQWtfYAx/Wy8zLUDuUJb/JL5OKeCPu27Xt1Yb0HWTZ9grHWbZiVs8oubLmuKJUtJOWy44aGg+VkWR/gttmNQRRr8QiIiTjHGWP7Jv3l/CYSXhUzvz7JCulq+IFGr0IbNXF0JnmxgdraTttKeRwT42/YST43Uz250q0hT2NTioAYJIhDhOfqQowGuruWR8ucSM0YMdhWabTjhOro8TaZc7HiRt9cARw9k8hF/aFUltys0fCkxKL82cyPcqwTAXbFipYuLCP8whiiJvnIJdCUB5dZj9xpKXXlRSzHbBBA3cM45thXE43Ut5qWxFM0pe9q7iR9pRMuC9zt9LrK98kocyX9vPeXBs8BW2HEkkbjPTxahBJ5jR32K1vT3K0pFE/zcMZRCgZvHxICyjiRo/Y6mkP/bVjY4i9l6K/3oHtxx7eiaRTeYBS21YYfEqjzt3HlSzY7nEbU5MQOx4s046J+wRG7LHYXzo2CBYtYNKbwp15MLvzL3D9hy1xPG80UsD8fzvjJMRD/pHMCt3W7dFcwiu7hCuVEWWHZuecxAl214fVD8zwJvCB6x1u/wnpAlxbVAweJFzSgnRtAUny0pQVfEU6v4WXcGBcKg="
