language: php
php:
  - "5.5.11"
  - "5.6"
  - "7.0"
  - "hhvm"

branches:
  only:
    - master
    - develop

before_script: bash .travis/before_script.sh
cache:
  directories:
    - vendor

script: bash .travis/script.sh

notifications:
  emails:
    - hiro.yo.yo1610+travis-ci@gmail.com
  on_success: never
  on_failure: always